# Generated by Django 4.2.8 on 2024-01-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_contents', '0002_format_subtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='format',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Content (내용)'),
        ),
        migrations.AddField(
            model_name='format',
            name='content_es',
            field=models.TextField(null=True, verbose_name='Content (내용)'),
        ),
        migrations.AddField(
            model_name='format',
            name='content_ja',
            field=models.TextField(null=True, verbose_name='Content (내용)'),
        ),
        migrations.AddField(
            model_name='format',
            name='content_ko',
            field=models.TextField(null=True, verbose_name='Content (내용)'),
        ),
        migrations.AddField(
            model_name='format',
            name='content_ru',
            field=models.TextField(null=True, verbose_name='Content (내용)'),
        ),
        migrations.AddField(
            model_name='format',
            name='content_zh',
            field=models.TextField(null=True, verbose_name='Content (내용)'),
        ),
    ]
