# Generated by Django 4.2.9 on 2024-01-31 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_contents', '0003_format_content_en_format_content_es_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='format',
            name='placeholders',
            field=models.TextField(blank=True, null=True, verbose_name='Placeholders'),
        ),
    ]
