# Generated by Django 4.2.9 on 2024-01-31 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_contents', '0004_format_placeholders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='format',
            old_name='placeholders',
            new_name='_placeholders',
        ),
    ]
