# Generated by Django 4.2.9 on 2024-02-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_contents', '0005_rename_placeholders_format__placeholders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='format',
            name='subtype',
            field=models.CharField(max_length=100, verbose_name='Sub Type (세부 유형)'),
        ),
    ]
