# Generated by Django 4.2.8 on 2023-12-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='생성일자')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='수정일자')),
                ('type', models.CharField(choices=[('ALARM', '알람'), ('HISTORY', '히스토리')], max_length=100, verbose_name='Type (유형)')),
                ('content', models.TextField(verbose_name='Content (내용)')),
            ],
            options={
                'verbose_name': 'format',
                'verbose_name_plural': 'formats',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='생성일자')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='수정일자')),
                ('field', models.TextField(blank=True, null=True, verbose_name='Field (필드)')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Content (내용)')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Link (링크)')),
                ('instance_id', models.TextField(blank=True, null=True, verbose_name='Instance ID (인스턴스 ID)')),
            ],
            options={
                'verbose_name': 'part',
                'verbose_name_plural': 'parts',
                'ordering': ['-created_at'],
            },
        ),
    ]
