# Generated by Django 4.2.8 on 2023-12-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_contents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='format',
            name='subtype',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sub Type (세부 유형)'),
        ),
    ]
